name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - uses: actions/checkout@v3
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          recursive: true
      - name: Print Hadolint lint results
        run: echo 'HADOLINT LINT RESULTS => ${{ env.HADOLINT_RESULTS }}'
